homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/London
  
  customize: !include_dir_merge_named customize
  customize_domain:
    automation:
      initial_state: 'on'
  packages: !include_dir_named packages

config:
http:
  base_url: !secret http_base_url
  server_port: !secret http_port
#  api_password: !secret http_api_password
#  ssl_certificate: !secret ssl_certificate
#  ssl_key: !secret ssl_key
  trusted_networks:
    - 192.168.1.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 3

frontend:
  javascript_version: latest


discovery:

updater:
  include_used_components: true

sun:
hue:
  bridges:
    - host: 192.168.10.75
      filename: phue.conf
      allow_unreachable: true
      allow_hue_groups: false

    - host: 192.168.10.76
      filename: phue2.conf
      allow_unreachable: true
      allow_hue_groups: false


# emulated_hue:
#   host_ip: 192.168.10.10
#   listen_port: 8300
#   expose_by_default: false

logger: !include logger.yaml

recorder: !include recorder.yaml

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

climate:
  platform: nest

group: !include_dir_merge_named group
device_tracker: !include_dir_merge_list device_tracker
sensor: !include_dir_merge_list sensor
automation: !include_dir_merge_list automation
scene: !include_dir_merge_list scene
switch: !include_dir_merge_list switch
script: !include_dir_merge_named script
input_boolean: !include_dir_merge_named input_boolean
shell_command: !include_dir_merge_named shell_command
