homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/London
  
  customize: !include_dir_merge_named customize
  customize_domain:
    automation:
      initial_state: 'on'
  packages: !include_dir_named packages

config:

http:
  base_url: !secret http_base_url
  server_port: !secret http_port
#  api_password: !secret http_api_password
#  ssl_certificate: !secret ssl_certificate
#  ssl_key: !secret ssl_key
  trusted_networks:
    - 192.168.1.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 3

frontend:
  javascript_version: latest

discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:


updater:
  include_used_components: true

sun:

hue:
  bridges:
    - host: 192.168.1.9
      filename: phue.conf
      allow_unreachable: true
      allow_hue_groups: false
   
vera:
  vera_controller_url: !secret vera_url

device_tracker:
  - platform: asuswrt
    host: !secret router_host
    username: !secret router_username
    password: !secret router_password
    
logger: !include logger.yaml

recorder: !include recorder.yaml

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables a map showing the location of tracked devices
map:

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

climate:
  platform: nest

switch rm:
  platform: broadlink
  host: !secret rmpro_host
  mac: !secret rmpro_mac
  type: rm2_pro_plus
  timeout: 15
  switches:
    zap1:
      friendly_name: "Jacks Socket"
      command_on: !secret zap1_on
      command_off: !secret zap1_off
    zap2:
      friendly_name: "Garden Lampost"
      command_on: !secret zap2_on
      command_off: !secret zap2_off
    zap3:
      friendly_name: "Zap Socket 3"
      command_on: !secret zap3_on
      command_off: !secret zap3_off
    zap4:
      friendly_name: "Zap Socket 4"
      command_on: !secret zap4_on
      command_off: !secret zap4_off
    zap5:
      friendly_name: "Zap Socket 5"
      command_on: !secret zap5_on
      command_off: !secret zap5_off

    kitchen_light:
      friendly_name: "Kitchen Light"
      command_on: !secret kitchen_light_on
      command_off: !secret kitchen_light_off

    kitchen_led:
      friendly_name: "Kitchen LED"
      command_on: !secret kitchen_led_on
      command_off: !secret kitchen_led_off

    lounge_light_toggle:
      friendly_name: "Lounge Light Toggle"
      command_on: !secret dimmer_1_on
      command_off: !secret dimmer_1_off
    lounge_light_1:
      friendly_name: "Lounge Button 1"
      command_on:  !secret dimmer_1_b1_on
      command_off: !secret dimmer_1_b1_off
    lounge_light_2:
      friendly_name: "Lounge Button 2"
      command_on:  !secret dimmer_1_b2_on
      command_off: !secret dimmer_1_b2_off
    lounge_light_3:
      friendly_name: "Lounge Button 3"
      command_on: !secret dimmer_1_b3_on
      command_off: !secret dimmer_1_b3_off
    lounge_light_dimmer:
      friendly_name: "Lounge Dimmer"
      command_on: !secret dimmer_1_dim_on
      command_off: !secret dimmer_1_dim_off


group: !include_dir_merge_named group
#device_tracker: !include_dir_merge_list device_tracker
sensor: !include_dir_merge_list sensor
automation: !include_dir_merge_list automation
scene: !include_dir_merge_list scene
switch: !include_dir_merge_list switch
script: !include_dir_merge_named script
#input_boolean: !include_dir_merge_named input_boolean
shell_command: !include_dir_merge_named shell_command
